# Generated by Django 2.2 on 2021-08-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rdv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_image')),
                ('titre', models.CharField(max_length=1000)),
                ('paragraphe', models.TextField(max_length=9999)),
            ],
        ),
    ]
