# Generated by Django 2.2 on 2021-08-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210813_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='paragraphe',
            field=models.CharField(max_length=9999),
        ),
    ]
